blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/heumsi/python-layer-dependency-linter/discussions
    about: Ask questions or start a discussion here.
